version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  web:
    build: .
    container_name: web
    env_file:
      - .env
    command: bash -c 'python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/home/user/web
    restart: always
    ports:
      - '8010:8000'
    expose:
      - 8010
    depends_on:
      - postgres
    networks:
      - web
      - internal

  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ./postgres/data/db:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - "POSTGRES_DB=${DATABASES_NAME}"
      - "POSTGRES_USER=${DATABASES_USER}"
      - "POSTGRES_PASSWORD=${DATABASES_PASSWORD}"
    networks:
      - internal
